home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('', views.index, name='home'),
    path('dashboard/ ', views.dashboard, name='dashboard')
]

project_manager/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from members.forms import NewAuthenticationForm
from project_manager import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls')),
                  path('', include('projects.urls')),
                  path('login/', views.LoginView.as_view(form_class=NewAuthenticationForm), name='login'),
                  path("password_reset/",
                       auth_views.PasswordResetView.as_view(template_name='registration/reset_password_form.html'),
                       name="password_reset"),
                  path(
                      "password_reset/done/",
                      auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_sent.html'),
                      name="password_reset_done",
                  ),
                  path('reset/<uidb64>/<token>/',
                       auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_set_form.html'),
                       name=" password_reset_confirm"),
                  path(
                      "reset/done/",
                      views.PasswordResetCompleteView.as_view(
                          template_name='registration/password_reset_confirmation.html'),
                      name="password_reset_complete",
                  ),
                  path('', include('django.contrib.auth.urls')),
                  path('', include('members.urls')),
                  path('', include('tasks.urls')),
                  path('', include('notifications.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path

from projects import views

urlpatterns=[
    path('create_project/', views.CreateProjectView.as_view(), name='create-project'),
    path('list_of_projects/', views.ListProjectView.as_view(), name='list-of-projects'),
    path('delete_project/<int:pk>/', views.DeleteProjectView.as_view(), name='delete-project'),
    path('update_project/<int:pk>/', views.UpdateProjectView.as_view(), name ='update-project'),
    path('detail_project/<int:project_id>/', views.detail_project, name='detail-project'),
    path('add_members_project/<int:project_id>', views.allocate_member_project, name='add-members-project'),
    path('my_projects/', views.user_project, name ='my-projects'),


]

projects/models.py
from django.contrib.auth.models import User

# Create your models here.
from django.db import models
from django.utils import timezone

from members.models import MemberUser
from notifications.models import Notifications


# Create your models here.

class Project(models.Model):
    project_status = [
        ('Planned', 'planned'),
        ('In Progress', 'in progress'),
        ('On Hold', 'on hold'),
        ('Completed', 'completed')
    ]
    priority_project = [
        ('Low', 'low'),
        ('High', 'high'),
        ('Medium', 'medium')
    ]
    name = models.CharField(max_length=100)
    description = models.TextField(null=True)
    start_date = models.DateTimeField(null=None)
    end_date = models.DateTimeField()
    status = models.CharField(max_length=30, choices=project_status)
    priority = models.CharField(max_length=30, choices=priority_project)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    team_members = models.ManyToManyField(MemberUser, related_name='team_project')

    def __str__(self):
        return self.name

    def check_deadline(self):
        """inregistrez notificarea cand proiectul ajunge la deadline"""
        if self.end_date <= timezone.now():
            notification = Notifications(receiver=self.owner,
                                         message=f"Your project '{self.name}' reached the deadline!")
            notification.save()

tasks/models.py
from datetime import timezone

from django.db import models

from members.models import MemberUser
from projects.models import Project


# Create your models here.
class Task(models.Model):
    priority_task = [
        ('Low', 'LOW'),
        ('Medium', 'MEDIUM'),
        ('High', 'HIGH')
    ]
    status_task = [
        ('To do', 'TO DO'),
        ('In progress', 'IN PROGRESS'),
        # ('Completed', 'COMPLETED')
    ]
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=100)
    description = models.TextField(default='')
    status = models.CharField(max_length=100, choices=status_task)
    priority = models.CharField(max_length=100, choices=priority_task)
    deadline = models.DateField()
    user = models.ForeignKey(MemberUser, on_delete=models.CASCADE, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

projects/forms.py
from django import forms

from members.models import MemberUser
from projects.models import Project


class ProjectForm(forms.ModelForm):
    class Meta:

        model = Project
        fields = ['name', 'description', 'start_date', 'end_date', 'status', 'priority']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter the project name'}),
            'description': forms.Textarea(
                attrs={'class': 'form-control', 'placeholder': 'Describe the project', 'rows': 5}),
            'start_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'end_date': forms.DateInput(attrs={"class": 'form-control', 'type': 'date'}),
            'status': forms.Select(attrs={'class': 'form-select'}),
            'priority': forms.Select(attrs={'class': 'form-select'})
        }

    def clean(self):
        cleaned_date = self.cleaned_data

        start_date = cleaned_date.get('start_date')
        end_date = cleaned_date.get('end_date')
        if start_date > end_date:
            msg = " Start date cannot be greater than the end date "
            self._errors['start_date'] = self.error_class([msg])

        project_name = cleaned_date.get('name')
        check_name = Project.objects.filter(name=project_name)
        if check_name:
            msg = " This Project already exists !"
            self._errors['name'] = self.error_class([msg])


class ProjectUpdateForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description', 'start_date', 'end_date', 'status', 'priority']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter the project name'}),
            'description': forms.Textarea(
                attrs={'class': 'form-control', 'placeholder': 'Describe the project', 'rows': 5}),
            'start_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'end_date': forms.DateInput(attrs={"class": 'form-control', 'type': 'date'}),
            'status': forms.Select(attrs={'class': 'form-select'}),
            'priority': forms.Select(attrs={'class': 'form-select'})
        }

    def clean(self):
        cleaned_date = self.cleaned_data

        start_date = cleaned_date.get('start_date')
        end_date = cleaned_date.get('end_date')
        if start_date > end_date:
            msg = " Start date cannot be greater than the end date "
            self._errors['start_date'] = self.error_class([msg])

        project_name = cleaned_date.get('name')
        check_name = Project.objects.filter(name=project_name)
        if check_name:
            msg = " This Project already exists !"
            self._errors['name'] = self.error_class([msg])


class ProjectAllocationMembersForm(forms.Form):
    team_members = forms.ModelMultipleChoiceField(
        queryset=MemberUser.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        label="Select memebers",
        required=False
    )

projects/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView

from members.models import MemberUser
from notifications.models import Notifications
from projects.forms import ProjectForm, ProjectUpdateForm, ProjectAllocationMembersForm
from projects.models import Project


# Create your views here.


class ListProjectView(LoginRequiredMixin, ListView):
    """
    afisez toate proiectele din BD
    """
    template_name = "projects/list_of_projects.html"
    model = Project
    context_object_name = "allprojects"

    def get_queryset(self):
        allprojects = Project.objects.exclude(status="Completed").all()
        return allprojects


class CreateProjectView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Project
    template_name = 'projects/create_project.html'
    form_class = ProjectForm
    success_url = reverse_lazy('create-project')
    success_message = 'The Project {name} has been successfully added!'

    def get_success_message(self, cleaned_data):
        return self.success_message.format(name=self.object.name)

    def form_valid(self, form):
        """
        owner= userul auth si cel care creeaza proiectul
        :param form:
        :return:
        """
        # if isinstance(self.request.user, MemberUser):
        #     Project.owner = self.request.user
        #     Project.save()

        form.instance.owner = self.request.user

        return super(CreateProjectView, self).form_valid(form)


@login_required
def detail_project(request, project_id):
    project = Project.objects.get(pk=project_id)
    project_members = project.team_members.all()
    return render(request, 'projects/detail_project.html', {'project': project, 'project_members': project_members})


class UpdateProjectView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Project
    success_url = reverse_lazy('list-of-projects')
    template_name = 'projects/update_project.html'
    form_class = ProjectUpdateForm
    success_message = f'The project {Project.objects.name} was successfuly updated'


class DeleteProjectView(LoginRequiredMixin, DeleteView):
    model = Project
    template_name = "projects/delete_project.html"
    success_url = reverse_lazy('list-of-projects')


@login_required
def allocate_member_project(request, project_id):
    """
    Alocare membrii disponibili pe proiect.
    Se afiseaza lista cu toti userii aplicatiei disponibili pt alocare pe proiecte.
    Trimit notificare catre user daca aloca membru pe proiect
    :param request:
    :param project_id:
    :return:
    """

    project = Project.objects.get(pk=project_id)
    form = ProjectAllocationMembersForm()
    if request.method == 'POST':
        form = ProjectAllocationMembersForm(request.POST)
        if form.is_valid():
            all_members = list(
                form.cleaned_data['team_members'].values_list('id', flat=True))  # iau toti membrii din aplicatie
            for member_id in all_members:
                # if member.id not in allocate_member_id:
                project.team_members.add(MemberUser.objects.get(id=member_id))
                project.save()
            notification = Notifications(receiver=project.owner,
                                         message=f"Ai alocat membru pe proiectul {project.name}")
            notification.save()
            return redirect('detail-project', project.id)
    else:
        team_members = MemberUser.objects.exclude(
            user_ptr_id__in=project.team_members.values_list("id", flat=False))

        project.check_deadline()

        return render(request, 'projects/add_member.html', {'team_members': team_members, "project": project.name})


@login_required()
def user_project(request):
    """
    afisez proiectele utilizatorului logat
    :param request:
    :return:
    """
    user = request.user  # stochez userul autentificat in var
    allprojects = Project.objects.filter(owner=user)
    project_member = Project.objects.filter(team_members=user)
    return render(request, 'projects/user_projects.html',
                  {'allprojects': allprojects, 'projectsmember': project_member})

templates/projects/add_member.html
{% extends 'base.html' %}
{% block title %} Members {% endblock %}
{% block content %}
    <br><br><br><br><br><br><br><br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-header">
                        <h2 class="text-center">Add Members for {{ project }}</h2>
                    </div>
                    <br>
                    <form method="post" enctype="multipart/form-data" class="text-center">
                        {% csrf_token %}
                        {% for user in team_members %}
                            <input type="checkbox" id="{{ user.id }}" name="team_members" value="{{ user.id }}">
                            <strong>{{ user.first_name }} {{ user.last_name }} - {{ user.position }} </strong><br><br>
                        {% endfor %}
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-danger">Add</button>
                            <a href="{% url 'my-projects' %}" class="btn btn-outline-secondary">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/projects/create_project.html
{% extends 'base.html' %}
{% block title %} Create Project {% endblock %}
{% block content %}
    <br><br><br><br><br><br><br><br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-success" role="alert">
                            <h3><strong>Congrats!</strong></h3> {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="card">
                    <div class="card-header">
                        <h2 class="text-center">Let's Work on it..</h2>
                    </div>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card-body">
                            {{ form.as_p }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="button" class="btn btn-danger" data-bs-toggle="modal"
                                    data-bs-target="#addModal">
                                Add Project
                            </button>
                            <div class="modal fade" id="addModal" tabindex="-1" aria-labelledby="ModalLabel"
                                 aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h1 class="modal-title fs-5" id="ModalLabel">Attention!</h1>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                    aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            <h4 class="text-primary">Are you sure you want to add the
                                                project {{ project.name }} ?</h4>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">
                                                No
                                            </button>
                                            <button type="submit" class="btn btn-danger">Yes</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <a href="{% url 'my-projects' %}" class="btn btn-outline-secondary">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/projects/delete_project.html
{% block content %}
    <div class="modal fade" tabindex="-1" role="dialog" id="deleteprojectModal{{ project.id }}" aria-hidden="true"
         aria-labelledby="detailModalLabel">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable"
             role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title" style="color: #d9232d"><strong> Delete {{ project }}</strong></h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <form method="post" enctype="multipart/form-data" action="{% url 'delete-project' project.id %}">
                    {% csrf_token %}
                    <div class="modal-body">
                        <p>Are you sure you want to delete {{ project }}?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-danger">Yes</button>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/projects/detail_project.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ project }} {% endblock %}
{% block content %}
    <div class="container"><br><br><br><br><br><br><br><br>
        <div class="row">
            <div class="col md-6 offset md-3">
                <div class="col-xxl-4 col-xl-3 col-lg-4 col-sm-5 col-12">
                    <h2 class="text-black fw-bolder mb-2">
                        {{ project.name }}
                    </h2>
                    <span class="badge-phoenix badge-phoenix-primary badge" style="background-color: darkred">
                            <span class="badge-label">{{ project.status }}</span>
                            </span>
                    <div class="gx-0 gx-sm-5 gy-8 mb-8 row">
                        <div class="pe-xl-0 col-xxl-4 col-xl-3 col-12">
                            <div class="mb-4 mb-xl-7">
                                <table class="lh-sm mb-3 mb-sm-0 mb-xl-3">
                                    <tbody>
                                    <tr>
                                        <td colspan="2" class="py-1"><i class="fa-solid fa-earth-americas"
                                                                        style="color: #d95e5e;"></i>
                                            Public Project
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="align-top py-1"><i class="fa-regular fa-user"
                                                                      style="color: #ea5353;"></i>
                                            Owner: {{ project.owner.first_name }}</td>
                                    </tr>
                                    </tbody>
                                </table>
                                <table class="1h-sm">
                                    <tbody>
                                    <tr>
                                        <td class="align-top py-1 text-900 text-nowrap fw-bold">Start
                                            Date: {{ project.start_date }}</td>
                                    </tr>
                                    <tr>
                                        <td class="align-top py-1 text-900 text-nowrap fw-bold">
                                            Deadline: {{ project.end_date }}</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="d-flex align-items-center">
                        <h5 class="text-1100 mb-0 me-2">
                            <i class="fa-solid fa-list-check"
                               style="color: #d35050;"></i> {{ project.task_set.count }} Tasks
                        </h5>
                    </div>
                    <br>
                </div>
            </div>
            <div class="col-xl-5 col-lg-8 col-sm-7 col-12">
                <i class="fa-solid fa-user-group"
                   style="color: #e15151;"></i>
                <h4 class="text-1100 mb-4">Team Members:</h4>
                <div class="d-flex mb-8 gap-1">
                    {% for member in project_members %}
                        {% if member.profile %}
                            <img src="{{ member.profile.url }}" class="rounded-circle"
                                 style="width: 50px; height: 50px;"
                                 alt="No image">
                        {% else %}
                            <p>No image</p>
                        {% endif %}
                    {% empty %}
                        <p> No members yet</p>

                    {% endfor %}
                </div>
            </div>
            <div>
                <h3 class="text-1100 mb-4">Project Description</h3>
                <p class="text-800 mb-4">{{ project.description }}</p>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

templates/projects/list_of_projects.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Projects {% endblock %}
{% block content %}
    <div class="container-fluid">
        <br><br><br><br>
        <div class="row">
            <div class="d-flex flex-wrap mb-4 gap-3 gap-sm-6 align-items-center">
                <div class="d-flex flex-wrap flex-stack my-5">
                    <strong>
                        <h2 class="mb-0"><span class="me-3">Projects</span>
                            <span class="fw-normal text-700"> ({{ allprojects.count }})</span>
                        </h2>
                    </strong>
                </div>
                <br>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-secondary" type="submit">Search</button>
                </form>
            </div>
        </div>

        <div class="row g-6 g-xl-9">
            {% for project in allprojects %}
                <div class="col-md-6 col-xl-4">
                    <a href="{% url 'detail-project' project.id %}" class="card border-hover-primary"
                       style="text-decoration: none">
                        <div class="card-header border-0 pt-9">
                            {#                                    card title#}
                            <div class="card-title m-0">
                            </div>
                            <div class="card-toolbar">
                                        <span class="badge badge-light-primary fw-bold me-auto px-4 py-2">
                                            {{ project.status }}
                                        </span>
                            </div>
                        </div>
                        <div class="card-body p-9">
                            <div class="fs-3 fw-bold text-dark"><b>{{ project.name }}</b></div>
                            <p class="text-gray-400 fw-semibold fs-5 mt-1 mb-7" style="color: gray">
                                Priority: {{ project.priority }}</p>
                            <div class="d-flex flex-wrap mb-5">
                                <div class="border border-gray-300 border-dashed rounded min-w-125px py-3 px-4 me-7 mb-3">
                                    <div class="fs-6 text-gray-800 fw-bold">
                                        {{ project.start_date }}
                                    </div>
                                    <div class="fw-semibold text-gray-400">Start Date</div>
                                </div>
                                <div class="border border-gray-300 border-dashed rounded min-w-125px py-3 px-4 me-7 mb-3">
                                    <div class="fs-6 text-gray-800 fw-bold">
                                        {{ project.end_date }}
                                    </div>
                                    <div class="fw-semibold text-gray-400">End Date</div>
                                </div>
                            </div>
                            <hr>
                            <p style="color: gray"><strong>Number of members: {{ project.team_members.count }}</strong>
                            </p>
                            <p style="color: gray"><strong>Owner: {{ project.owner.first_name }}</strong></p>
                        </div>
                    </a><br>
                </div>
            {% endfor %}
        </div>
    </div>
    </div>
    </div>
{% endblock %}

templates/projects/update_project.html
{% extends 'base.html' %}
{% block title %} {{ project }} {% endblock %}
{% block content %}
    <br><br><br><br><br>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">{{ project }}</h3>
                    </div>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card-body">
                            {{ form.as_p }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-danger">Save</button>
                            <a href="{% url 'list-of-projects' %}" class="btn btn-outline-secondary">Cancel</a>
                        </div>
                    </form>

                </div>
            </div>
{% endblock %}